deepspeed --module scripts.train_simpo \
    --model-path /data/hf_models/Meta-Llama-3.1-8B-Instruct/ \
    --dataset-paths /data/jbb/datas/Skywork-Reward-80k-Formatted \
    --sample-counts 80 \
    --sample-counts-eval 10 \
    --max-data-length 128000 \
    --max-packing-length 0 \
    --micro-batch-size 1 \
    --global-batch-size 8 \
    --prompt-key chat_template \
    --chosen-key chosen \
    --rejected-key rejects \
    --num-rejects 1 \
    --simpo-gamma 0.5 \
    --simpo-beta 2.5 \
    --simpo-nll-loss-weight 0.05 \
    --save-name Test-Loom-Llama3.1-simpo \
    --tensorboard-logdir ./tensorboard